name: CI

on:
  merge_group:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

concurrency:
  # Skip intermediate builds: all builds except for builds on the `main` branch
  # Cancel intermediate builds: only pull request builds
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.ref != 'refs/heads/main' || github.run_number }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

permissions:
  contents: read

jobs:
  finalize:
    timeout-minutes: 10
    needs: [test, format]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo test: ${{ needs.test.result }}
          echo test: ${{ needs.format.result }}
      - run: exit 1
        if: |
          (needs.test.result != 'success') ||
          (needs.format.result != 'success')

  test:
    permissions:
      actions: write
      contents: read
    runs-on: ${{ matrix.os }}
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.6"
          - "1.10.0"
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        # macOS 1.6 seems to consistently stall on `Plots` notebooks. Skip this
        # combination and test on a slightly newer macOS version instead.
        exclude:
          - version: "1.6"
            os: macos-latest
        include:
          - version: "1.7"
            os: macos-latest
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          persist-credentials: false

      - uses: r-lib/actions/setup-r@b7e68d63e51bdf225997973e2add36d551f60f02
        with:
          use-public-rspm: true
          r-version: "4.4"
      - run: echo "LD_LIBRARY_PATH=$(R RHOME)/lib:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        if: matrix.os == 'ubuntu-latest'

      - uses: julia-actions/setup-julia@f2258781c657ad9b4b88072c5eeaf9ec8c370874
        with:
          version: ${{ matrix.version }}
      - uses: julia-actions/cache@dc1a3cdeacb521b0ca93cfc66143fcadb15a5bd0
      - uses: julia-actions/julia-buildpkg@90dd6f23eb49626e4e6612cb9d64d456f86e6a1c
      - uses: julia-actions/julia-runtest@79a7e100883947123f8263c5f06e6c0ea3eb972f
        with:
          depwarn: "yes"
      - uses: julia-actions/julia-processcoverage@03114f09f119417c3242a9fb6e0b722676aedf38
      - uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed
        with:
          verbose: true
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@f2258781c657ad9b4b88072c5eeaf9ec8c370874
        with:
          version: "1"
      - run: |
          julia --project=.ci -e 'using Pkg; Pkg.instantiate(); Pkg.precompile()'
          julia --project=.ci .ci/format.jl
